version: '3.9'
services:
  postgres-db:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: simpleToDo_local
      POSTGRES_PASSWORD: simpleToDo_local
      POSTGRES_DB: simpleToDo
