spring:
  application:
    name: simpleToDo
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/data/simpleTodo
    driverClassName: org.h2.Driver
    username: simpleToDoUser
    password: password
    hikari:
      auto-commit: false
  devtools: # Should only happen on local
    livereload:
      enabled: true
    restart:
      enabled: false
  h2:
    console:
      enabled: true # Should only happen on local
  jpa:
    show-sql: true # Should only happen on local
    open-in-view: false
#  thymeleaf:
#    cache: false