spring:
  application:
    name: simpleToDo
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleToDo
    driverClassName: org.postgresql.Driver
    username: simpleToDo_local
    password: simpleToDo_local
    hikari:
      auto-commit: false
  devtools: # Should only happen on local
    livereload:
      enabled: true
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true # Should only happen on local
#  thymeleaf:
#    cache: false