spring:
  application:
    name: simpleToDo
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/simpleToDo?user=simpleToDo_local&password=simpleToDo_local}
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  devtools: # Should only happen on local
    livereload:
      enabled: true
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true # Should only happen on local
  port: ${PORT:8080}
#  thymeleaf:
#    cache: false